export const globeAddress = [
  "Upper Ground Floor Ali Mall II Araneta Center Cubao Quezon City",
  "2nd Floor Eastwood Mall Eastwood City Cyberpark E. Rodriguez Avenue Bagumbayan Quezon City",
  "3054 Drive Brgy Pasong Putik Novaliches QC",
  "3rd Floor Gateway Mall Araneta Center Cubao Quezon City",
  "Ground Floor Montalban Town Center Rodriguez Highway cor. Lardizabal Street Rodriguez Rizal",
  "Unit 103 A Ground Floor National Bookstore Inc. Quezon Avenue Quezon City",
  "3F Robinsons Magnolia Aurora Boulevard cor. Doña Hemady and Domingo Streets. New Manila Quezon City",
  "3rd Floor Cyberzone SM City Fairview Quirino Highway Cor. Regalado Avenue Barangay Greater Lagro Novaliches Quezon City",
  "Ground Floor Cyberzone SM City Marikina Marcos Highway Calumpang Marikina City",
  "2nd Floor Cyberzone SM City Masinag Marcos Highway Antipolo City",
  "4/F Cyberzone Bldg New SM Annex SM City North Edsa  Quezon City",
  "2nd Floor SM City Novaliches Quirino Highway San Bartolome 2 Novaliches Quezon City",
  "2nd Floor Building B SM City Taytay Manila East Road Taytay Rizal ",
  "3rd Floor SM Super Center Valenzuela Mc Arthur Highway Valenzuela City",
  "Level 3 Building 3 Sta. Lucia Mall Marcos Highway cor. Felix Avenue Cainta Rizal",
  "M1 Unit 1034 Trinoma Mall EDSA Quezon City",
  "Ground Floor Alphaland Southgate Mall EDSA cor. Pasong Tamo Extension Makati City",
  "Ground Floor Glorietta 3 Ayala Center Makati City",
  "2nd Floor Greenbelt 4 Ayala Center Makati City",
  "The Globe Tower 32nd St. 7th Ave",
  "4th Floor Market Market Bonifacio Global City Taguig",
  "Level R2 Power Plant Mall Rockwell Makati City",
  "Level 1 East Wing Robinsons Galleria Mall EDSA cor. Ortigas Avenue Quezon City",
  "Level 1 Shangri-la Plaza EDSA cor. Shaw Boulevard Mandaluyong City",
  "Level 4 Unit 434 SM Aura Premiere 26th Street cor. McKinley Parkway Brgy. Fort Bonifacio Global City 1630 Taguig City",
  "3F CZ4 Cyberzone Area SM City BF Paranaque",
  "4th Floor Concourse Area SM Makati Department Store Ayala Center Makati City",
  "4th Floor Cyberzone SM Megamall Building B Ortigas Center Pasig City",
  "Ground Floor V Mall Greenhills Shopping Center Ortigas Avenue San Juan",
  "2nd Floor Alabang Town Center Madrigal cor. Commerce Avenue Alabang Muntinlupa",
  "Level 3 Filinvest Festival Supermall Filinvest Corporate City Alabang Muntinlupa City",
  "3rd Floor Lucky China Town Mall Calle Felipe cor. La Chombre Streets Barangay 293 Zone 28 Binondo Manila",
  "Level 4 Pedro Gil Wing Robinsons Place Manila Pedro Gil cor. Adriatico Streets Ermita Manila",
  "2nd Floor SM City Bicutan Building B Dona Soledad Avenue Barangay Don Bosco Bicutan Paranaque City",
  "2nd Floor North Parking Building SM Mall of Asia Pasay City",
  "Lower Ground Floor Cyberzone SM City Manila Arroceros cor. Marcelino Streets Manila",
  "2nd Floor SM Supercenter Muntinlupa National Road Tunasan Muntinlupa City",
  "3rd Floor SM City San Lazaro Felix Huertas cor. A.H. Lacson Streets Sta. Cruz Manila",
  "3rd Floor Cyberzone SM Southmall Alabang-Zapote Road Las Pinas City",
  "3rd Floor SM City Sta. Mesa Ramon Magsaysay Boulevard cor. Araneta Sta. Mesa Manila",
  "3rd Level SM Supercenter Sucat Sucat Road Paranaque City",
  "Unit 154 Robinsons Place Pangasinan McArthur Highway Barangay San Miguel Calasiao Pangasinan",
  "KanPing Commercial Building Maharlika Highway Barangay San Antonio f City Ilocos Sur",
  "Manlapaz Bldg cor Quezon Streets National Highway District 1 Cauayan City Isabela",
  "GF Citimart Bauan Kap. Ponso St. Bauan Batangas",
  "Ground Floor 127 Nepo Mall Dagupan Arellano Avenue Dagupan Pangasinan",
  "Ground Floor SM Hypermart F.R Castro cor. Paco Roman Streets Laoag City Ilocos Norte",
  "#15 Palaris Street San Carlos City Pangasinan",
  "Ground Floor La Union Provincial Administrative Commercial Building Quezon Avenue San Fernando La Union",
  "365 Plaza LG-9 National Highway Barangay 1 San Francisco San Nicolas Ilocos Norte",
  "AKC Building National Highway Villasis Santiago City Isabela",
  "3rd Floor SM City Baguio Luneta Hill Upper Session Road Baguio City",
  "Ground Floor SM City Rosales MacArthur Highway Barangay Carmen East  Rosales Pangasinan",
  "National Highway Poblacion South Solano Nueva Vizcaya",
  "Unit 79 Chowking Building Balzain Road Tuguegarao City Cagayan Valley",
  "Collegio Business Center Mart One Nueva Segovia Street Vigan City",
  "Recar Commercial Complex JP Rizal Barangay Poblacion Balanga City",
  "Ground Level GL-4B NE Pacific Mall Km. 111 Maharlika Highway Cabanatuan City Nueva Ecija",
  "Gen 3 SM Cabanatuan 2nd floor Cyberzone SM City Cabanatuan Maharlika Highway Cabanatuan City",
  "Ground Floor Suarez Bldg. Timbol Street San Nicolas Concepcion Tarlac",
  "2nd Floor Graceland Mall MacArthur Highway Barangay Ginhawa Malolos Bulacan",
  "Ground Floor Waltermart-Guiguinto McArthur Highway Ilang-Ilang Guiguinto Bulacan",
  "Ground Floor Harbor Point Mall Rizal Avenue Subic Bay Freeport Zone Olongapo City",
  "Ground Floor Marquee Mall Francisco G. Nepomuceno Avenue Pulong Maragul Angeles City Pampanga",
  "3rd Floor SM City Olongapo RM Drive cor. Gordon Avenue Barangay Pag-asa Olongapo City",
  "Ground Floor Starmall San Jose Del Monte Quirino Highway cor. Kaypian Road Barangay Kaypian San Jose Del Monte City Bulacan",
  "Mokara Building Maharlika Road San Jose City",
  "Ground Floor SM City Baliwag Doña Remedios Trinidad Highway Barangay Pagala Baliuag Bulacan",
  "2nd Floor SM City Clark Clarkfield Pampanga",
  "2nd Floor SM City Marilao Km. 21 Barangay Ibayo MacArthur Highway Bulacan",
  "Ground Floor Cyberzone SM City Pampanga Barangay San Jose San Fernando Pampanga",
  "3rd Floor SM City San Fernando V. Tiomico Street Barangay Poblacion San Fernando City Pampanga",
  "3rd Floor Cyberzone SM City Tarlac MacArthur Highway Tarlac City",
  "Grid E-F & 1-2 Waltermart Plaridel Cagayan Valley Road Barrio Banga 1 Plaridel Bulacan",
  "Ground Floor Waltermart Mac Arthur Highway Barangay San Agustin San Fernando City Pampanga",
  "Ground Floor Waltermart Sta. Maria Provincial Road cor. By Pass Road Barangay Sta. Clara Sta. Maria Bulacan",
  "Space #53 Solenad 2 Barangay Sto. Domingo Sta. Rosa City Laguna",
  "Sunstar Mall National Highway Gatid Sta. Cruz Laguna",
  "GF G-40 Ayala Serin Aguinaldo Highway Brgy.Maharlika East Tagaytay City Cavite",
  "Ground Floor Waltermart Tanauan Tanauan City Batangas",
  "2F E204 SM Dasmarinas Governor Drive 1 Brgy. Sampaloc Dasmarinas Cavite",
  "3rd Floor Cyberzone SM City Bacoor Tirona Highway cor. Aguinaldo Highway Bacoor Cavite",
  "2nd Floor Cyberzone SM City Calamba National Highway Barangay Real Calamba City",
  "2nd Floor SM Supercenter Molino Molino IV Bacoor Cavite",
  "2nd Floor SM City Rosario General Trias Drive Rosario Cavite",
  "2nd Floor SM City San Pablo Maharlika Highway San Pablo City",
  "2nd Floor SM City Sta. Rosa Barangay Tagapo Sta. Rosa City Laguna",
  "Tanay Town Center F.T. Catapusan Street Sampaloc Road Barangay Plaza Aldea Tanay",
  "2nd Floor Target Mall Balibago Complex Sta. Rosa City",
  "Ground Floor The District Ayala Mall Imus Cavite",
  "Ultimart Shopping Plaza M. Paulino St. San Pablo City Laguna",
  "G/F Homemark Bldg JP Rizal St. Camilmil Calapan City Or. Mindoro",
  "G/F Unit 112B The District Ayala Mall Imus Cavite",
  "GF-28 Central Mall Salitran II Dasmarinas Cavite",
  "Tan Building J. Pimentel St. Daet Camarines Norte",
  "2nd Level LCC Mall Iriga Barangay San Francisco Highway 1 Iriga City",
  "G/F RVC Bldg. Ilustre Ave. cor. A. Bonifacio St. Lemery Batangas",
  "JP Laurel cor. F. Alix Streets. Nasugbu Batangas City",
  "2nd Level Pacific Mall Landco Business Park Bitano Legaspi City",
  "FCA Bldg 2 Mabini Street Zone 3 Pinamalayan Oriental Mindoro",
  "Unit 1 Ground Floor GETAN Square 273 Rizal Avenue Puerto Princesa Palawan",
  "Stall #11 CHUA Commercial Complex Lapu-lapu Street Barangay 4 San Jose Occidental Mindoro",
  "2nd Floor SM City Batangas Pastor Village Pallocan West Batangas City",
  "Ground flr. Robinsons PLace J P Laurel Lipa City",
  "2nd Floor SM City Lipa Ayala Highway Lipa City Batangas",
  "3rd Floor Cyberzone SM City Lucena Dalahican cor. Pagbilao Roads Lucena City",
  "2nd Floor SM City Naga Central Business II Barangay Triangulo Naga City",
  "Active Zone Ayala Center Cebu Cebu Business Park Cebu City",
  "G/F Grace Space Rental Enterprise A. Bonifacio St. Baybay City Leyte",
  "Ground Floor Sim Building P. Rodriguez Street Bogo City Cebu",
  "2nd Level Wilsam Uptown Mall Borongan Samar",
  "Unit #2 Crown Building Magsaysay Boulevard Calbayog City Western Samar",
  "Ground Floor Gaisano Prize Club Carcar Poblacion 3 Awayan Carcar City Cebu",
  "G/F First Choice Hotel Del Rosario St. Catbalogan City 6700",
  "G/F Main entrance (below the escalator) Colonade Mall Colon St. Cebu City",
  "3rd Level Elizabeth Mall Bacalso cor. Leon Kilat Streets Cebu City",
  "Ground Floor Annex-5 Gaisano Island Mall Pajo Lapulapu City Cebu",
  "Ground floor beside main entrance Pering Chai Bio Building Tomas Oppos Street Tunga-Tunga Maasin City",
  "Ground Floor Gaisano Grand Mall Mactan Agus cor. Basak Roads Lapulapu City Cebu",
  "2nd Floor Gaisano Grand Fiesta Mall Tabunok Talisay City Cebu",
  "17 G/F Gaisano Grand Mall Riverside Sangi Toledo City",
  "2F Units 16 & 17 Galleria Luisa Governor Celestino Gallares St. Tagbilaran City Bohol",
  "Lower Ground Floor Island City Mall Dao District Tagbilaran City",
  "Upper G/F - GK16 J. Center Mall A.S. Fortuna Mandaue City",
  "MFT Bldg. Real St. Ormoc City",
  "2nd Level Pacific Mall Ibabao Street Estancia Mandaue City",
  "2nd Floor Cyberzone SM City Cebu Northwing North Reclamation Area Cebu City",
  "2nd Floor Cyberzone SM City Consolacion Lamac Consolacion Cebu",
  "Ground Floor Sorsogon Shopping Center Magsaysay Street Sorsogon City",
  "Ground Floor Annex Building Robinsons Place Tacloban National Highway Tabuan Marasbaras Tacloban City Leyte",
  "Level1 Stall F123 The District North Point Talisay City",
  "27th cor. Lacson Streets Mandalangan Bacolod City",
  "Phase 2 Block C Unit 2A D Mall de Boracay Balabag Boracay Island Malay Aklan",
  "2nd Floor Gaisano City La Paz Iloilo City",
  "LG - 26A Ground Floor Gaisano Grand Mall Roxas Arnaldo Boulevard Roxas City Capiz",
  "Gaisano Grand Mall Tan Lorenzo Street Kabankalan City Negros Occidental",
  "Ground Floor Maria Gracia Bldng. Roxas Avenue cor. L . Barrios St. Kalibo Aklan",
  "Ground Floor GF-06 Gaisano Capital Oton J.C. Zulueta St. corner Benecdito St. Oton Iloilo City",
  " 3rd Level Robinsons Place Mandalagan Bacolod City ",
  "Space 276-279 Level 2 Robinsons Dumaguete Calindagan Dumaguete City Negros Oriental",
  "2nd Floor Robinsons Place Pueblo de Panay Roxas City Capiz",
  "Door 3 ATB Building Maranon Street Poblacion II Sagay City",
  "National Highway cor. Ledesma Avenue San Carlos City Negros Occidental",
  "AML Building corner Dalipe and Atabay San Jose Antique",
  "Unit 209 - 210 Cyberzone 2/F North Wing SM City Reclamation Area Bacolod City 6100",
  "Ground Floor SM City Delgado Delgado cor. Valeria Streets Delgado Iloilo City ",
  "2nd Floor SM City Iloilo B. Aquino Avenue Mandurriao Iloilo City",
  "Magallanes Street Poblacion 9 Tanjay City Negros Oriental",
  "2nd Floor Ayala Centrio Mall Lapasan Cagayan de Oro City",
  "3rd Level Gaisano Mall J.C. Aquino Avenue Butuan City",
  "New Concourse Limketkai Mall Lapasan Cagayan de Oro City",
  "Unit M2 111 West Promenade Limketkai Mall Lapasan Cagayan De Oro",
  "Lee Plaza City Central Quezon Avenue Miputak Dipolog City 7100",
  "3rd Floor Gaisano Mall Roxas Avenue Villa Verde Iligan City",
  "Ground Floor Malaybalay Glassware Fortich Street Barangay 3 Malaybalay City Bukidnon",
  "Ground Floor Gaisano Ozamis City Mall Rizal Avenue cor. Zamora Extension Ozamiz City",
  "Lower Ground Gaisano Capital Pagadian City",
  "2nd Floor Gaisano CDO C.M. Recto Avenue Corner Corals Extension Cagayan De Oro City",
  "3rd Floor SM City CDO Gran Via cor. Mastersons Avenue Cagayan De Oro City",
  "LML Bldg. Rizal St. Washington Surigao City 8400",
  "2nd Floor NVM Building Sayre Highway Valencia City Bukidnon",
  "Ground Floor Lobby VIP Hotel Don A. Velez Street Cagayan De Oro City",
  "BPI Building Makakua Street Cotabato City",
  "3rd Level Abreeza Mall J.P. Laurel Avenue Davao City",
  "2nd Floor NCCC Mall McArthur Highway Matina Davao",
  "Ground Floor Gaisano Grand Mall Quezon Avenue Digos City Davao del Sur",
  "KCC Mall of Gensan J. Catolico Avenue General Santos City",
  "4F KCC Mall of Marbel Gensan Drive Koronadal City South Cotabato 9506",
  "2nd Level Cyberzone SM Annex Bldg. SM City Davao Ecoland Quimpo Blvd. Davao City 8000",
  "3rd Floor SM Gensan Santiago Boulevard cor. San Miguel Street General Santos City",
  "3F Cyberzone SM lanang Premier JP Laurel Avenue Bajada Davao City",
  "3/f Gaisano Mall of Tagum National Highway Tagum City 8100",
  "Door 2&3 ARV Bldg. San Jose Road Zamboanga City",
  "2nd Floor Southway Square Don P.Lorenzo St. cor. Gov. Lim Avenue Zone 4 Zamboanga City"

]
